name: CI

on:
  push:
    tags: [ 'v*' ]
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v2.4.0
      - name: Setup build dependencies
        run: |
          npm install
          sudo apt-get update
          sudo apt-get install -y reuse gnome-shell-extensions gettext

      - name: Run linter
        run: make lint

      - name: Build gnome-extension ZIP file
        run: make zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          generate_release_notes: true
          files: |
            target/default/battery-indicator-icon@Deminder.shell-extension.zip
